<?php

function pingpong_menu() {
    $items['pingpong'] = array(
        'title' => 'Ping Pong!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('pingpong_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['pingpong_success_page'] = array(
        'title' => 'Ping Pong Results',
        'page callback' => 'pingpong_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function pingpong_form() {
    $form['pingpong_number'] = array(
        '#title' => 'Enter a number',
        '#type' => 'textfield',
        '#description' => t('Please enter a number to pingpong.'),
        '#element_validate' => array('element_validate_integer_positive'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate ping pong list!',
    );
    return $form;
}

function pingpong_form_submit($form, &$form_state) {
    $pingpong_number = $form_state['values']['pingpong_number'];
    $pingpong_output = array();

    for ($i=1; $i <= $pingpong_number; $i++) {
        if ($i % 3 == 0 && $i % 5 == 0) {
            array_push($pingpong_output, "ping-pong");
        } elseif ($i % 3 == 0) {
            array_push($pingpong_output, "ping");
        } elseif ($i % 5 == 0) {
            array_push($pingpong_output, "pong");
        } else {
            array_push($pingpong_output, $i);
        }
    }

    $_SESSION['pingpong_output'] = $pingpong_output;
    $form_state['redirect'] = 'pingpong_success_page';
}

function pingpong_success() {
    $output = '<ul>';
    foreach ($_SESSION['pingpong_output'] as $value) {
        $output = $output . '<li>' . $value . '</li>';
    }
    $output = $output . '</ul>';
    return "Horray! $output";
}
