<?php

function shifter_menu() {
  $items['shifter'] = array(
    'title' => 'Shift your text!',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shifter_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['shifter_results_page'] = array(
    'title' => 'Shifter results',
    'page callback' => 'shifter_results',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function shifter_form() {
  $form['shift_value'] = array(
      '#title' => 'How many letters do you want to shift over?!',
      '#type' => 'textfield',
      '#description' => t('Enter a number'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
  );
  $form['shift_direction'] = array(
      '#title' => 'Which direction would you like to shift?',
      '#type' => 'textfield',
      '#description' => t('Enter \'left\' or \'right\''),
      '#element_validate' => array('element_validate_direction'),
      '#required' => TRUE,
  );
  $form['shift_phrase'] = array(
      '#title' => 'Enter a phrase!',
      '#type' => 'textfield',
      '#description' => t('Enter a phrase'),
      '#element_validate' => array('element_validate_phrase'),
      '#required' => TRUE,
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Shift it!',
  );
  return $form;
}
function element_validate_direction($element) {
    if ((strtolower($element['#value']) != 'left') && (strtolower($element['#value']) != 'right')) {
        form_error($element, t('Please enter left or right!'));
    }
}

function element_validate_phrase($form, &$form_state) {
    $shift_phrase = strtolower($form_state['values']['shift_phrase']);
    if (!preg_match('/^[a-zA-Z0-9,.!? ]*$/', $shift_phrase)) {
        form_set_error('shift_phrase', t('Please only include letters, numbers, and regular special characters.'));
    }
}


    function shifter_form_submit($form, &$form_state) {

        $shift_value = $form_state['values']['shift_value'];
        $shift_direction = ($form_state['values']['shift_direction']);
        $shift_phrase = strtolower($form_state['values']['shift_phrase']);

        $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'
    , 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
        $offsets = array_flip($alphabet);
        $shift_phrase_split = str_split($shift_phrase);
        $phrase_length = count($shift_phrase_split);

        $shift_result = '';

        $shift_flip = array_flip($shift_phrase_split);
            if ($shift_direction === 'left') {
                for ($i = 0; $i < $phrase_length; $i++) {

                  $shift_result .= $alphabet[(($offsets[$shift_phrase_split[$i]]-$shift_value)+2600000000000000000) % 26];
                }
            }
            else {
                for ($i = 0; $i < $phrase_length; $i++) {

                  $shift_result .= $alphabet[(($offsets[$shift_phrase_split[$i]]+$shift_value)+2600000000000000000) % 26];
                }
            }

        $_SESSION['shift_value'] = $shift_value;
        $_SESSION['shift_direction'] = $shift_direction;
        $_SESSION['shift_phrase'] = $shift_phrase;
        $_SESSION['shift_result'] = $shift_result;
        $form_state['redirect'] = 'shifter_results_page';
    }

    function shifter_results() {

        $result = $_SESSION['shift_result'];
        $phrase = $_SESSION['shift_phrase'];
        $direction = strtolower($_SESSION['shift_direction']);
        $value = $_SESSION['shift_value'];
        return '<h2>Phrase you shifted: <strong>' . $phrase . '</strong><br>Direction you shifted: <strong>' . $direction . '</strong><br>How many letters you shifted over: <strong>' . $value . '</strong><br>Your shifted result is <strong>' . $result . '</strong></h2>';
  }
