<?php

function shifter_menu() {
  $items['shifter'] = array(
    'title' => 'Shift your text!',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shifter_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['shifter_results_page'] = array(
    'title' => 'Shifter results',
    'page callback' => 'shifter_results',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function shifter_form() {
  $form['shift_value'] = array(
      '#title' => 'How many letters do you want to shift over?!',
      '#type' => 'textfield',
      '#description' => t('Enter a number'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
  );
  $form['shift_direction'] = array(
      '#title' => 'Which direction would you like to shift?',
      '#type' => 'textfield',
      '#description' => t('Enter \'left\' or \'right\''),
      '#element_validate' => array('element_validate_direction'),
      '#required' => TRUE,
  );
  $form['shift_phrase'] = array(
      '#title' => 'Enter a phrase!',
      '#type' => 'textfield',
      '#description' => t('Enter a phrase'),
      '#required' => TRUE,
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Shift it!',
  );
  return $form;
}
function element_validate_direction($element) {
    if ((strtolower($element['#value']) != 'left') && (strtolower($element['#value']) != 'right')) {
        form_error($element, t('Please enter left or right!'));
    }
}


    function shifter_form_submit($form, &$form_state) {

        $shift_value = $form_state['values']['shift_value'];
        $shift_direction = $form_state['values']['shift_direction'];
        $shift_phrase = $form_state['values']['shift_phrase'];

        $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'
    , 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
        $shift_phrase_split = str_split($shift_phrase);
        $offsets = array_flip($alphabet);
        $phrase_length = count($shift_phrase_split);

        $shifter_result = '';

        $shift_flip = array_flip($shift_phrase_split);

        for ($i = 0; $i < $phrase_length; $i++) {

          $shifter_result .= $alphabet[($offsets[$shift_phrase_split[$i]]+$shift_value)%26];
        }

        // $imploded_result = implode($shifter_result);
        $_SESSION['shifter_output'] = $shifter;
        $_SESSION['shifter_count'] = $phrase_length;
        $_SESSION['shift_flip'] = $shift_flip;
        $_SESSION['shifter_result'] = $shifter_result;
        // $_SESSION['imploded'] = $imploded_result;
        $form_state['redirect'] = 'shifter_results_page';
    }

  function shifter_results() {

    $result = $_SESSION['shifter_result'];
  return 'Your shifted result is ' . $result;
  }
